"""added cover column

Revision ID: 20477311f276
Revises: 84a84ec8c593
Create Date: 2024-10-11 17:20:35.381276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20477311f276'
down_revision: Union[str, None] = '84a84ec8c593'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('description', sa.String(), nullable=True))
    op.add_column('articles', sa.Column('cover', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'cover')
    op.drop_column('articles', 'description')
    # ### end Alembic commands ###